// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomBookingBackend.Data;

#nullable disable

namespace RoomBookingBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RoomBookingBackend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RoomBookingBackend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 120,
                            Description = "Ruangan luas di lantai 1 gedung D4. Fasilitas: 6 Kipas Angin, layar proyektor.",
                            IsDeleted = false,
                            Name = "Hall D4"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            Description = "Ruangan kelas di lantai 2 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "B.201"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 60,
                            Description = "Ruangan kelas di lantai 2 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "B.202"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 40,
                            Description = "Ruangan kelas di lantai 2 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "B.203"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 120,
                            Description = "Ruangan kelas di lantai 2 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "B.204"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 40,
                            Description = "Ruangan kelas di lantai 2 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "B.205"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 120,
                            Description = "Ruangan kelas di lantai 3 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "A.301"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 60,
                            Description = "Ruangan kelas di lantai 3 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "A.302"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 120,
                            Description = "Ruangan kelas di lantai 3 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "A.303"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 40,
                            Description = "Ruangan kelas di lantai 3 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "A.304"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 60,
                            Description = "Ruangan kelas di lantai 3 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "B.301"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 40,
                            Description = "Ruangan kelas di lantai 3 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "B.302"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 120,
                            Description = "Ruangan kelas di lantai 3 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "B.303"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 60,
                            Description = "Ruangan kelas di lantai 3 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "B.304"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 40,
                            Description = "Ruangan kelas di lantai 3 gedung D4. Fasilitas: 1 Kipas Angin, 1 AC, layar proyektor.",
                            IsDeleted = false,
                            Name = "B.305"
                        });
                });

            modelBuilder.Entity("RoomBookingBackend.Models.Booking", b =>
                {
                    b.HasOne("RoomBookingBackend.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomBookingBackend.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
